### ISSUE TITLE
RecyclerViewMergeAdapter:2.0.0 : IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by guruduttstay** [martijnvdwoude/recycler-view-merge-adapter#7]
hi 

Just upgraded to recyclerviewmergeadapter:2.0.0

And getting this issue all over place several time 

Though this is no consistent but happens a lot and app crashes and restarts 

NB : I am already having one issue at one place : https://github.com/martijnvdwoude/recycler-view-merge-adapter/issues/4#issuecomment-250506056

but after upgrade this issue is occurring few more places now 

May be you want to have look.

```



java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 62(offset:62).state:153
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4503)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)
                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
                                                              at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1162)
                                                              at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1019)
                                                              at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1399)
                                                              at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2347)
                                                              at android.view.View.dispatchTouchEvent(View.java:9300)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                              at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                              at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                              at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                              at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                              at android.view.View.dispatchPointerEvent(View.java:9520)
                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                            at android.view.ViewRootImpl.enqueueInputEve


```

Others similar crashes : 

```
09-30 08:01:54.606 25627-25627/com.stay E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.stay, PID: 25627
                                                          java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:132).state:27
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4503)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)
                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2801)
                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
                                                              at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
                                                              at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                              at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
                                                              at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                              at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                              at android.view.View.layout(View.java:16636)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                              at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by guruduttstay** [comment]
I had wrongly notified dataset change .... not getting anymore

**Comment by guruduttstay** [comment]
I am getting this crash or https://github.com/martijnvdwoude/recycler-view-merge-adapter/issues/4#issuecomment-250506056

**Comment by guruduttstay** [comment]
It's matter of how recycler is notified about dataSet changes so this is no a issue from this library so closing it
